import 'server-only';
import { getPool } from './db';
import { getAgentById } from './agents';
import { getListings } from './listings';

/**
 * Public agent storefront (web/app/(site)/agents/[id]/page.js) — reuses
 * lib/agents.js's getAgentById (Phase 2) rather than re-querying agents/
 * vendors/agent_infos/memberships/packages from scratch, and adds the two
 * things that query doesn't need for the admin table: a bio and the
 * listings feed itself.
 */

/**
 * vendor_infos is per-language, same as agent_infos (confirmed: vendor #36
 * has two rows) — LATERAL + LIMIT 1, same fix Phase 2 already had to make
 * for agent_infos, to avoid fanning out here too.
 */
export async function getAgentProfile(id) {
  const agent = await getAgentById(id);
  if (!agent) return null;

  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT details FROM vendor_infos
     WHERE vendor_id = $1
     ORDER BY (language_id = 20) DESC, language_id
     LIMIT 1`,
    [agent.vendor_id],
  );

  return { ...agent, bio: rows[0]?.details || null };
}

/**
 * @param {number} agentId
 * @param {{transactionType?: string, propertyType?: string, commune?: string, limit?: number, offset?: number}} [filters]
 */
export async function getAgentListings(agentId, filters = {}) {
  return getListings({ ...filters, agentId, limit: filters.limit ?? 24 });
}

/**
 * Private dashboard (Phase 4D) — deliberately NOT getListings()/getAgentListings():
 * those apply APPROVED_FILTER (status=1 AND approve_status=1), which is
 * correct for the public storefront but wrong here — an agent managing
 * their own listings needs to see a pending/rejected one too, not have it
 * silently vanish from their own dashboard.
 */
export async function getOwnListingsForDashboard(agentId) {
  const pool = getPool();
  const { rows } = await pool.query(
    `SELECT p.id, p.price, p.purpose, p.beds, p.approve_status, p.listing_status, p.featured_image, p.quartier,
            p.sold_price, p.sold_at, p.archived_at, p.status, p.created_at,
            p.currency, p.price_original, pc.title
     FROM properties p
     JOIN property_contents pc ON pc.property_id = p.id AND pc.language_id = 20
     WHERE p.agent_id = $1
     ORDER BY p.created_at DESC`,
    [agentId],
  );
  return rows;
}

/**
 * The one display-name computation every agent-dashboard page needs —
 * previously duplicated ad hoc per file (and with a different fallback
 * string in each copy). Also what submitInquiryAction
 * (web/app/(site)/agents/[id]/actions.js) writes into a general inquiry's
 * `assigned_agent` column, so the dashboard's own lead queries can match
 * against it exactly — see services/db.js's listLeads doc comment.
 */
export function agentDisplayName(agent) {
  return [agent?.first_name, agent?.last_name].filter(Boolean).join(' ') || agent?.username || null;
}

/**
 * Real save path behind the design's "Identité de l'agence" settings card.
 *
 * Both target tables are per-language content tables with NO unique
 * constraint on (agent_id, language_id) — verified directly against the
 * live schema, along with the fact that `id` on both is
 * `GENERATED BY DEFAULT AS IDENTITY` with a real sequence, so an INSERT may
 * omit it. No unique constraint means `ON CONFLICT` has nothing to target,
 * hence UPDATE-then-INSERT rather than a one-statement upsert.
 *
 * The INSERT branch is not hypothetical: `createAgent` (lib/agents.js) only
 * ever writes the `agents` row, so an agent who signed up through this app's
 * own phone+password flow has no agent_infos/vendor_infos row at all, and an
 * UPDATE-only implementation would silently save nothing for exactly the
 * agents most likely to use this form.
 *
 * Writes only the French row (language_id 20) — the same row every read path
 * here already prefers (see getAgentProfile / lib/agents.js's LATERAL joins).
 * A second-language row, where one exists, is left untouched rather than
 * being overwritten with French copy.
 */
const FRENCH_LANGUAGE_ID = 20;

export async function updateAgentIdentity(agentId, { firstName, lastName, bio, vendorId }) {
  const pool = getPool();

  const { rowCount: infoUpdated } = await pool.query(
    `UPDATE agent_infos SET first_name = $1, last_name = $2, updated_at = NOW()
     WHERE agent_id = $3 AND language_id = $4`,
    [firstName || null, lastName || null, agentId, FRENCH_LANGUAGE_ID],
  );
  if (infoUpdated === 0) {
    await pool.query(
      `INSERT INTO agent_infos (agent_id, language_id, first_name, last_name, created_at, updated_at)
       VALUES ($1, $2, $3, $4, NOW(), NOW())`,
      [agentId, FRENCH_LANGUAGE_ID, firstName || null, lastName || null],
    );
  }

  // The bio is read from vendor_infos.details (see getAgentProfile), so it
  // is written back to exactly that column — not agent_infos.details, which
  // also exists but is never read by this app and would strand the value.
  if (vendorId) {
    const { rowCount: bioUpdated } = await pool.query(
      `UPDATE vendor_infos SET details = $1, updated_at = NOW()
       WHERE vendor_id = $2 AND language_id = $3`,
      [bio || null, vendorId, FRENCH_LANGUAGE_ID],
    );
    if (bioUpdated === 0) {
      await pool.query(
        `INSERT INTO vendor_infos (vendor_id, language_id, details, created_at, updated_at)
         VALUES ($1, $2, $3, NOW(), NOW())`,
        [vendorId, FRENCH_LANGUAGE_ID, bio || null],
      );
    }
  }
}

export async function updateAgentImage(agentId, imageUrl) {
  const pool = getPool();
  await pool.query('UPDATE agents SET image = $1, updated_at = NOW() WHERE id = $2', [imageUrl, agentId]);
}

/**
 * Same write admin's updateAgentCommunesAction (web/app/admin/agents/actions.js)
 * already proves against agents.primary_communes — pulled in here so the
 * agent's own self-service action can share it instead of re-deriving the SQL.
 */
export async function updateAgentCommunes(agentId, communes) {
  const pool = getPool();
  await pool.query('UPDATE agents SET primary_communes = $1, updated_at = NOW() WHERE id = $2', [
    communes,
    agentId,
  ]);
}

export async function updateAgentWorkingHours(agentId, workingHours) {
  const pool = getPool();
  await pool.query('UPDATE agents SET working_hours = $1, updated_at = NOW() WHERE id = $2', [
    workingHours || null,
    agentId,
  ]);
}

/**
 * The design's sidebar carries a "Profil complété — 82 %" card with a
 * progress bar and a next-step hint. 82 % is sample data; this computes the
 * real figure from fields that genuinely exist on this schema and genuinely
 * affect what a visitor sees on the public storefront — nothing is counted
 * that the agent can't actually act on, and the hint names the real next
 * gap rather than a canned string.
 *
 * `listingCount` comes from lib/agents.js's own correlated subquery on the
 * agent row, so this needs no extra query of its own.
 *
 * @returns {{percent: number, done: number, total: number, nextHint: string|null}}
 */
export function agentProfileCompletion(agent, { listingCount } = {}) {
  const checks = [
    {
      label: 'Nom renseigné',
      // A REAL name, not the phone-digits fallback. `createAgent` sets
      // `username` to the agent's own phone number, so a plain truthiness
      // check on agentDisplayName marks this complete for an account that
      // has never set a name — and the public page then shows a phone
      // number where the agency name belongs while the checklist claims
      // the step is done.
      done: !!(agent?.first_name || agent?.last_name) || !/^\d{9,15}$/.test(agent?.username || ''),
      hint: 'Ajoutez votre nom pour personnaliser votre page.',
    },
    { label: 'Présentation rédigée', done: !!agent?.bio, hint: 'Ajoutez une présentation de votre agence.' },
    { label: 'Numéro WhatsApp', done: !!agent?.phone, hint: 'Ajoutez votre numéro WhatsApp.' },
    {
      label: 'Numéro vérifié',
      done: !!agent?.phone_verified_at,
      hint: 'Vérifiez votre numéro pour afficher le badge « Numéro vérifié ».',
    },
    { label: 'Photo de profil', done: !!agent?.image, hint: 'Ajoutez une photo de profil.' },
    {
      label: 'Communes couvertes',
      done: !!agent?.primary_communes?.length,
      hint: 'Indiquez les communes que vous couvrez.',
    },
    {
      label: 'Au moins un bien publié',
      done: (listingCount ?? agent?.listing_count ?? 0) > 0,
      hint: 'Publiez votre premier bien via WhatsApp.',
    },
  ];

  const done = checks.filter((c) => c.done).length;
  return {
    percent: Math.round((done / checks.length) * 100),
    done,
    total: checks.length,
    items: checks.map(({ label, done: isDone }) => ({ label, done: isDone })),
    nextHint: checks.find((c) => !c.done)?.hint || null,
  };
}
