-- Agent verification tiers and the documents behind them.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260917_agent_verification.sql --write
--
-- MUST RUN BEFORE the web deploy that reads `agents.verification_level`
-- (lib/listings.js and lib/agents.js select it on every public listing and
-- agent read — without the column those queries fail outright).
--
-- ADDITIVE AND IDEMPOTENT. NO BACKFILL: every agent starts at 'standard',
-- because nobody has reviewed anybody's documents yet, and stamping a level
-- would record a review that never happened.
--
-- WHY A LEVEL + TIMESTAMP, NOT `is_verified boolean`
-- Every comparable flag on this schema is a timestamp (phone_verified_at,
-- verified_at, sold_at), for the reason root CLAUDE.md gives: a bare boolean
-- cannot answer "who said so, and when". `is_verified` is derived in SQL as
-- `verification_level IN ('verified', 'agency_partner')`.
--
-- WHY THIS IS NOT phone_verified_at
-- phone_verified_at: this PERSON holds this NUMBER (OTP / WhatsApp onboarding).
-- verification_level: a human on the team REVIEWED this person's identity
-- documents ('verified') and, for 'agency_partner', the agency's RCCM too.
-- Two different claims; the green public badge is the second one.

BEGIN;

ALTER TABLE agents ADD COLUMN IF NOT EXISTS verification_level varchar(20) NOT NULL DEFAULT 'standard';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'agents_verification_level_check') THEN
    ALTER TABLE agents ADD CONSTRAINT agents_verification_level_check
      CHECK (verification_level IN ('standard', 'verified', 'agency_partner'));
  END IF;
END $$;

ALTER TABLE agents ADD COLUMN IF NOT EXISTS verification_reviewed_at timestamptz;
-- console_admin_users.id. NULL under the shared bootstrap password, honestly —
-- same convention as properties.verified_by.
ALTER TABLE agents ADD COLUMN IF NOT EXISTS verification_reviewed_by bigint;

-- The files live in a PRIVATE Storage bucket (SUPABASE_VERIFICATION_BUCKET,
-- created by web/scripts/setup-verification-bucket.js). Only the object path
-- is stored; the console opens a document through a 5-minute signed URL, and
-- every opening is audited. Never a public URL: these are ID cards.
CREATE TABLE IF NOT EXISTS agent_verification_documents (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id       bigint       NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  doc_type       varchar(20)  NOT NULL CHECK (doc_type IN ('id_card', 'passport', 'rccm', 'other')),
  storage_path   text         NOT NULL,
  original_name  text,
  mime_type      varchar(60)  NOT NULL,
  size_bytes     integer      NOT NULL,
  status         varchar(20)  NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  review_note    text,
  reviewed_at    timestamptz,
  reviewed_by    bigint,
  created_at     timestamptz  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS agent_verification_documents_queue_idx
  ON agent_verification_documents (status, created_at);
CREATE INDEX IF NOT EXISTS agent_verification_documents_agent_idx
  ON agent_verification_documents (agent_id, created_at DESC);

REVOKE ALL ON agent_verification_documents FROM anon, authenticated;

COMMIT;
