-- The landlord's live report link: lukkaplace.com/rapport/<id>-<signature>.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260929_property_report_links.sql --write
--
-- ADDITIVE AND IDEMPOTENT. One new table. web/lib/reportLinks.js answers
-- "unavailable" on 42P01, so web can deploy first.
--
-- An agent creates the link once and forwards it to the owner; the page it
-- opens always shows current numbers, so nobody has to send a new report every
-- week. One ACTIVE link per listing (partial unique index): "regenerate"
-- revokes the old row and creates a new one, which is how an agent cuts off
-- an owner who should no longer see it.
--
-- NO SECRET IS STORED HERE. The URL's signature is an HMAC of
-- (id, property_id, nonce) under a server secret (REPORT_LINK_SECRET), so a
-- copy of this table alone cannot open any report, while the agent can still
-- be shown their link again at any time (it is recomputed, never looked up).
--
-- The page shows a listing's public facts and counts only — no customer
-- names, numbers or messages. `view_count` / `last_viewed_at` let the agent see
-- that the owner opened it; the agent's own openings are not counted.

BEGIN;

CREATE TABLE IF NOT EXISTS property_report_links (
  id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id     bigint      NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
  agent_id        bigint      REFERENCES agents (id) ON DELETE SET NULL,
  nonce           text        NOT NULL CHECK (char_length(nonce) BETWEEN 16 AND 64),
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  revoked_at      timestamptz,
  last_viewed_at  timestamptz,
  view_count      integer     NOT NULL DEFAULT 0 CHECK (view_count >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS property_report_links_active_key
  ON property_report_links (property_id) WHERE revoked_at IS NULL;

DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON property_report_links FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
