-- Engagement tracking: who is behind the numbers, and the steps we did not see.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260929_engagement_tracking.sql --write
--
-- ADDITIVE AND IDEMPOTENT. New columns, one new table, new rollup columns.
-- web/lib/trackIngest.js and web/lib/leadClicks.js retry without the new
-- columns on 42703 (and skip a search on 42P01), so web can deploy before or
-- after this runs without losing a single view.
--
-- WHAT THIS ADDS
--
-- 1. `visitor_id` on the three event tables. A random first-party id the
--    browser keeps in the `lp_vid` cookie (web/lib/analyticsClient.js). It
--    carries no personal data and is never shown to anyone: it exists so a
--    landlord report can say "38 personnes différentes" instead of "120
--    ouvertures de page", which counts the same visitor five times. NULL on
--    every row written before this ran, and never backfilled — there is no
--    honest way to say which old rows were the same person.
--
-- 2. `page_views.listing_id`. Every per-listing reader parsed it out of
--    `path` (`substring(path FROM 11)`); a real column is both cheaper and
--    harder to get wrong. Backfilled below from the path itself, which is a
--    derivation, not an invention: `/listings/310` IS listing 310.
--
-- 3. `listing_events.routing_type`: DIRECT | CENTRAL on a `call_click`, i.e.
--    whether the tel: link rang the listing's verified agent or Lukka Place's
--    central number (web/lib/leadRouting.js decides which). NULL on every
--    other event. Deliberately not whatsapp_clicks' DIRECT_WA vocabulary:
--    a phone call is not a WhatsApp tap.
--
-- 4. `search_events`: one row per distinct search a visitor committed on
--    /listings, with the number of listings that matched it EXACTLY (before
--    any relaxation). `result_count = 0` is unmet demand — "2 ch à Limete
--    < 500 $, 41 recherches, 0 biens" — which is what a developer or a bank
--    wants to know and what localStorage-only search history could never
--    tell us.
--
-- 5. New listing_stats_daily columns, filled by the engine's
--    services/listingStatsRollup.js: calls, gallery_opens, gallery_completes,
--    shares, unique_visitors (per day — a weekly "personnes" figure is
--    counted from raw events, since summing daily uniques double-counts a
--    returning visitor) and visit_requests (from the engine's own SQLite).

BEGIN;

ALTER TABLE page_views      ADD COLUMN IF NOT EXISTS visitor_id text;
ALTER TABLE page_views      ADD COLUMN IF NOT EXISTS listing_id bigint;
ALTER TABLE whatsapp_clicks ADD COLUMN IF NOT EXISTS visitor_id text;
ALTER TABLE listing_events  ADD COLUMN IF NOT EXISTS visitor_id text;
ALTER TABLE listing_events  ADD COLUMN IF NOT EXISTS routing_type text;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'listing_events_routing_type_check') THEN
    ALTER TABLE listing_events ADD CONSTRAINT listing_events_routing_type_check
      CHECK (routing_type IS NULL OR routing_type IN ('DIRECT', 'CENTRAL'));
  END IF;
END $$;

-- Derived from the path, never guessed: only an exact `/listings/<digits>`.
UPDATE page_views
   SET listing_id = substring(path FROM 11)::bigint
 WHERE listing_id IS NULL
   AND path ~ '^/listings/[0-9]{1,18}$';

CREATE INDEX IF NOT EXISTS page_views_listing_created_idx ON page_views (listing_id, created_at);
-- "How many different people" per listing and window.
CREATE INDEX IF NOT EXISTS page_views_listing_visitor_idx ON page_views (listing_id, visitor_id) WHERE visitor_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS listing_events_event_listing_created_idx ON listing_events (event, listing_id, created_at);

CREATE TABLE IF NOT EXISTS search_events (
  id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id     text,
  -- 'rent' | 'sale', the storefront's own purpose vocabulary; NULL = both.
  purpose        text        CHECK (purpose IS NULL OR purpose IN ('rent', 'sale')),
  communes       text[]      NOT NULL DEFAULT '{}' CHECK (cardinality(communes) <= 5),
  quartier       text,
  property_type  text,
  beds_min       smallint    CHECK (beds_min IS NULL OR beds_min BETWEEN 0 AND 50),
  price_min      numeric(14, 2) CHECK (price_min IS NULL OR price_min >= 0),
  price_max      numeric(14, 2) CHECK (price_max IS NULL OR price_max >= 0),
  -- The "Plus de filtres" keys (web/lib/constants.js AMENITY_GROUPS) — and,
  -- later, the structured utility codes.
  amenities      text[]      NOT NULL DEFAULT '{}' CHECK (cardinality(amenities) <= 20),
  q              text        CHECK (q IS NULL OR char_length(q) <= 200),
  -- Listings matching the search EXACTLY, before any relaxation widened it.
  result_count   integer     NOT NULL CHECK (result_count >= 0),
  device         text,
  source         text,
  created_at     timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS search_events_created_idx ON search_events (created_at);
CREATE INDEX IF NOT EXISTS search_events_zero_idx ON search_events (created_at) WHERE result_count = 0;

ALTER TABLE listing_stats_daily ADD COLUMN IF NOT EXISTS calls             integer NOT NULL DEFAULT 0;
ALTER TABLE listing_stats_daily ADD COLUMN IF NOT EXISTS gallery_opens     integer NOT NULL DEFAULT 0;
ALTER TABLE listing_stats_daily ADD COLUMN IF NOT EXISTS gallery_completes integer NOT NULL DEFAULT 0;
ALTER TABLE listing_stats_daily ADD COLUMN IF NOT EXISTS shares            integer NOT NULL DEFAULT 0;
ALTER TABLE listing_stats_daily ADD COLUMN IF NOT EXISTS unique_visitors   integer NOT NULL DEFAULT 0;
ALTER TABLE listing_stats_daily ADD COLUMN IF NOT EXISTS visit_requests    integer NOT NULL DEFAULT 0;

-- Nothing reads these over the REST API. Same posture as listing_stats_daily.
DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON search_events FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
