-- Market history: every asking-price and status change, monthly snapshots, and
-- a flag that keeps test accounts out of the market data.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260929_market_history.sql --write
--
-- ADDITIVE AND IDEMPOTENT. New tables, trigger functions (CREATE OR REPLACE),
-- triggers (dropped and re-created), one new column on agents.
--
-- WHY TRIGGERS
-- properties is written by the engine's sync, web's agent and admin actions,
-- the WhatsApp availability loop, backfill scripts and the moderators. A
-- history written by each of them would miss whichever one forgot. A trigger
-- is ONE definition of "the price changed" that no writer can skip.
--
-- The trigger never fails the write it observes: its body catches every error
-- and raises a WARNING. Losing one history row is recoverable; refusing an
-- agent's price change because history could not be written is not.
--
-- `source` comes from the transaction-local setting `lukka.change_source`,
-- which services/postgres.js setListingPrice sets (set_config(..., true) —
-- never a bare SET on the Supabase pooler); anything else records 'direct'.
--
-- BASELINE, NOT INVENTED HISTORY
-- One `source = 'baseline'` row per existing listing, stamped with the time
-- this migration ran: the state at the moment capture started. Nothing
-- earlier is reconstructed — the old prices were overwritten and are gone.
--
-- NO FOREIGN KEY TO properties on the history tables, on purpose: an agent can
-- delete a listing, and a sold listing's price path is market data that must
-- outlive it.

BEGIN;

CREATE TABLE IF NOT EXISTS property_price_history (
  id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id     bigint      NOT NULL,
  price           numeric,
  price_original  numeric,
  currency        text,
  purpose         text,
  price_period    text,
  source          text        NOT NULL,
  changed_at      timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS property_price_history_property_idx ON property_price_history (property_id, changed_at);
CREATE INDEX IF NOT EXISTS property_price_history_changed_idx ON property_price_history (changed_at);

CREATE TABLE IF NOT EXISTS property_status_history (
  id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id     bigint      NOT NULL,
  status          integer,
  approve_status  integer,
  listing_status  text,
  archived        boolean     NOT NULL DEFAULT false,
  source          text        NOT NULL,
  changed_at      timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS property_status_history_property_idx ON property_status_history (property_id, changed_at);
CREATE INDEX IF NOT EXISTS property_status_history_changed_idx ON property_status_history (changed_at);

CREATE OR REPLACE FUNCTION lukka_record_price_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  BEGIN
    IF TG_OP = 'INSERT'
       OR NEW.price IS DISTINCT FROM OLD.price
       OR NEW.price_original IS DISTINCT FROM OLD.price_original
       OR NEW.currency IS DISTINCT FROM OLD.currency
       OR NEW.purpose IS DISTINCT FROM OLD.purpose
       OR NEW.price_period IS DISTINCT FROM OLD.price_period THEN
      INSERT INTO property_price_history (property_id, price, price_original, currency, purpose, price_period, source)
      VALUES (NEW.id, NEW.price, NEW.price_original, NEW.currency, NEW.purpose, NEW.price_period,
              COALESCE(NULLIF(current_setting('lukka.change_source', true), ''), 'direct'));
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'property_price_history not written for %: %', NEW.id, SQLERRM;
  END;
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION lukka_record_status_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  BEGIN
    IF TG_OP = 'INSERT'
       OR NEW.status IS DISTINCT FROM OLD.status
       OR NEW.approve_status IS DISTINCT FROM OLD.approve_status
       OR NEW.listing_status IS DISTINCT FROM OLD.listing_status
       OR (NEW.archived_at IS NULL) IS DISTINCT FROM (OLD.archived_at IS NULL) THEN
      INSERT INTO property_status_history (property_id, status, approve_status, listing_status, archived, source)
      VALUES (NEW.id, NEW.status, NEW.approve_status, NEW.listing_status, NEW.archived_at IS NOT NULL,
              COALESCE(NULLIF(current_setting('lukka.change_source', true), ''), 'direct'));
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'property_status_history not written for %: %', NEW.id, SQLERRM;
  END;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS properties_price_history ON properties;
CREATE TRIGGER properties_price_history
  AFTER INSERT OR UPDATE OF price, price_original, currency, purpose, price_period ON properties
  FOR EACH ROW EXECUTE FUNCTION lukka_record_price_change();

DROP TRIGGER IF EXISTS properties_status_history ON properties;
CREATE TRIGGER properties_status_history
  AFTER INSERT OR UPDATE OF status, approve_status, listing_status, archived_at ON properties
  FOR EACH ROW EXECUTE FUNCTION lukka_record_status_change();

-- The state at capture start, once per listing (re-runs add nothing).
INSERT INTO property_price_history (property_id, price, price_original, currency, purpose, price_period, source)
SELECT p.id, p.price, p.price_original, p.currency, p.purpose, p.price_period, 'baseline'
  FROM properties p
 WHERE NOT EXISTS (SELECT 1 FROM property_price_history h WHERE h.property_id = p.id);

INSERT INTO property_status_history (property_id, status, approve_status, listing_status, archived, source)
SELECT p.id, p.status, p.approve_status, p.listing_status, p.archived_at IS NOT NULL, 'baseline'
  FROM properties p
 WHERE NOT EXISTS (SELECT 1 FROM property_status_history h WHERE h.property_id = p.id);

-- Monthly supply snapshots (services/marketSnapshot.js). Written once per
-- month and never updated: "what the data said in March" stays what it said.
-- Raw medians and their sample size are stored; the MIN_SAMPLE suppression is
-- applied where they are shown, so the rule can change without losing data.
CREATE TABLE IF NOT EXISTS market_snapshots_monthly (
  month                 date        NOT NULL,
  commune               text        NOT NULL,
  purpose               text        NOT NULL CHECK (purpose IN ('rent', 'sale')),
  category_id           integer     NOT NULL,   -- 0 = no category, -1 = every type (the commune total)
  beds_bucket           text        NOT NULL,   -- '0'..'3', '4+', 'na', 'all' (the commune total)
  active_count          integer     NOT NULL DEFAULT 0,
  new_count             integer     NOT NULL DEFAULT 0,
  median_ask            numeric,
  p25_ask               numeric,
  p75_ask               numeric,
  ask_sample            integer     NOT NULL DEFAULT 0,
  median_ask_per_sqm    numeric,
  sqm_sample            integer     NOT NULL DEFAULT 0,
  price_cut_count       integer     NOT NULL DEFAULT 0,
  closed_count          integer     NOT NULL DEFAULT 0,
  median_achieved       numeric,
  median_gap_pct        numeric,
  achieved_sample       integer     NOT NULL DEFAULT 0,
  median_days_to_close  numeric,
  withdrawn_count       integer     NOT NULL DEFAULT 0,
  computed_at           timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (month, commune, purpose, category_id, beds_bucket)
);

-- Demand has no property type (a customer asks for "2 chambres à Limete"), so
-- it is its own table on the dimensions it really has.
CREATE TABLE IF NOT EXISTS market_demand_monthly (
  month                 date        NOT NULL,
  commune               text        NOT NULL,
  purpose               text        NOT NULL CHECK (purpose IN ('rent', 'sale', 'any')),
  beds_bucket           text        NOT NULL,
  leads                 integer     NOT NULL DEFAULT 0,
  searches              integer     NOT NULL DEFAULT 0,
  zero_result_searches  integer     NOT NULL DEFAULT 0,
  computed_at           timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (month, commune, purpose, beds_bucket)
);

-- Test and demo accounts ("Agence Test") are real rows in production. Their
-- listings are excluded from every market figure, snapshot and export —
-- a bank must never be shown a price someone typed to try the product.
ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_test boolean NOT NULL DEFAULT false;

DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON property_price_history FROM %I', role_name);
      EXECUTE format('REVOKE ALL ON property_status_history FROM %I', role_name);
      EXECUTE format('REVOKE ALL ON market_snapshots_monthly FROM %I', role_name);
      EXECUTE format('REVOKE ALL ON market_demand_monthly FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
