-- Projets: buildings sold/let by unit type, off-plan developments, and land
-- sold in lots or portions ("lotissement / morcellement").
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260924_developments.sql --write
--
-- ADDITIVE AND IDEMPOTENT. New tables only; nothing on `properties` changes.
-- web/lib/developments.js treats a missing table (42P01) as "no projects yet",
-- so the web deploy is safe before or after this runs.
--
-- WHY A SEPARATE ENTITY AND NOT MORE `properties` ROWS
-- A multi-unit WhatsApp paste already becomes N `properties` rows sharing a
-- `parent_building_id` (one map pin, see web/lib/buildingGroups.js). That is
-- right for a handful of real, individually available units. A developer's
-- 40-unit tower, a building not yet built, or a plot cut into lots is a
-- different thing: it is marketed by TYPE ("2 chambres, dès 900 $, 4 dispo"),
-- it has a construction stage and a delivery date, and a lot plan has no
-- equivalent on a listing. Forcing it into `properties` would mean 40
-- near-identical rows or invented per-door facts.
--
-- VISIBILITY: the same two integers as `properties`, and the same public gate:
--   status = 1 AND approve_status = 1
-- Created by the Lukka Place team from /admin/projets (approve_status stays 0
-- until someone publishes it).
--
-- VERIFICATION is a timestamp, like properties.verified_at: "we checked the
-- permit, the land title and visited the site", set only by a human. Never
-- backfilled, never derived.
--
-- NOTHING IS AGGREGATED. units_available lives on each unit type and lot status
-- on each lot; "7 dispo · dès 900 $" is computed at read time, never stored
-- (same rule as scripts/migrate-building-columns.js).

BEGIN;

CREATE TABLE IF NOT EXISTS developments (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                text        NOT NULL UNIQUE,
  name                text        NOT NULL,
  -- 'building' = an immeuble / résidence (off-plan or delivered);
  -- 'land'     = a plot sold in lots or in portions.
  kind                text        NOT NULL CHECK (kind IN ('building', 'land')),
  -- Buildings only. NULL on land.
  stage               text        CHECK (stage IS NULL OR stage IN ('pre_launch', 'under_construction', 'delivered')),
  delivery_expected   date,
  -- What is on offer: 'sale', 'rent', or both across unit types.
  purpose             text        NOT NULL DEFAULT 'sale' CHECK (purpose IN ('sale', 'rent', 'mixed')),
  -- The developer / agency account marketing it. SET NULL: deleting an agent
  -- must not delete a project the team published.
  agent_id            bigint      REFERENCES agents (id) ON DELETE SET NULL,
  developer_name      text,
  commune             text,
  quartier            text,
  address             text,
  latitude            double precision,
  longitude           double precision,
  description         text,
  amenities           text[]      NOT NULL DEFAULT '{}',
  -- Real photographs of the site / building as it is.
  photos              text[]      NOT NULL DEFAULT '{}',
  -- Architectural renders. Always shown labelled "Image d'illustration" and
  -- never mixed into `photos`.
  renders             text[]      NOT NULL DEFAULT '{}',
  video_url           text,
  -- [{ "label": "À la réservation", "percent": 30 }, ...] — must sum to 100
  -- when present (checked by web/lib/developmentRules.js, not here: a partial
  -- plan being edited is a legitimate intermediate state).
  payment_plan        jsonb       NOT NULL DEFAULT '[]'::jsonb,
  -- Land: the whole plot and the site plan the lots are traced on.
  land_area_m2        numeric,
  land_title_status   text        CHECK (land_title_status IS NULL OR land_title_status IN ('own_title', 'shared_title', 'in_progress', 'unknown')),
  plan_image          text,
  status              smallint    NOT NULL DEFAULT 1,
  approve_status      smallint    NOT NULL DEFAULT 0,
  verified_at         timestamptz,
  verified_by         text,
  verification_note   text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_at          timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS developments_public_idx ON developments (created_at DESC)
  WHERE status = 1 AND approve_status = 1;
CREATE INDEX IF NOT EXISTS developments_agent_idx ON developments (agent_id);

CREATE TABLE IF NOT EXISTS development_unit_types (
  id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  development_id    bigint      NOT NULL REFERENCES developments (id) ON DELETE CASCADE,
  label             text        NOT NULL,
  purpose           text        NOT NULL DEFAULT 'sale' CHECK (purpose IN ('sale', 'rent')),
  bedrooms          integer,
  bathrooms         integer,
  area_m2           numeric,
  price_min         numeric,
  price_max         numeric,
  -- Rent only: 'month' (default) or 'year'.
  price_period      text        CHECK (price_period IS NULL OR price_period IN ('month', 'year')),
  units_total       integer,
  units_available   integer,
  floor_plan_image  text,
  sort_order        integer     NOT NULL DEFAULT 0,
  created_at        timestamptz NOT NULL DEFAULT NOW(),
  updated_at        timestamptz NOT NULL DEFAULT NOW(),
  CHECK (units_available IS NULL OR units_available >= 0),
  CHECK (units_total IS NULL OR units_available IS NULL OR units_available <= units_total)
);
CREATE INDEX IF NOT EXISTS development_unit_types_dev_idx ON development_unit_types (development_id, sort_order);

-- Construction timeline: dated progress photos. `taken_on` is the date the
-- photos show, entered by a person — not created_at, which is when someone
-- typed it in.
CREATE TABLE IF NOT EXISTS development_updates (
  id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  development_id  bigint      NOT NULL REFERENCES developments (id) ON DELETE CASCADE,
  taken_on        date        NOT NULL,
  caption         text,
  photos          text[]      NOT NULL DEFAULT '{}',
  created_at      timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS development_updates_dev_idx ON development_updates (development_id, taken_on DESC);

-- Land lots / portions. A "portion" (30 % / 50 % / 100 % of one plot) is a
-- lot with share_percent set; a traced lot plan is a lot with a polygon.
-- `polygon` is [[x, y], ...] in the plan image's own 0..1000 coordinate box.
CREATE TABLE IF NOT EXISTS development_lots (
  id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  development_id  bigint      NOT NULL REFERENCES developments (id) ON DELETE CASCADE,
  label           text        NOT NULL,
  area_m2         numeric,
  price           numeric,
  share_percent   numeric     CHECK (share_percent IS NULL OR (share_percent > 0 AND share_percent <= 100)),
  status          text        NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'reserved', 'sold')),
  title_status    text        CHECK (title_status IS NULL OR title_status IN ('own_title', 'shared_title', 'in_progress', 'unknown')),
  polygon         jsonb,
  sort_order      integer     NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS development_lots_dev_idx ON development_lots (development_id, sort_order);

-- Supabase grants anon/authenticated on new public tables by default; the
-- storefront reads through its own server-side pool, never PostgREST. Same
-- posture as listing_shares and the console_* tables.
DO $$
DECLARE
  role_name TEXT;
  table_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      FOREACH table_name IN ARRAY ARRAY['developments', 'development_unit_types', 'development_updates', 'development_lots'] LOOP
        EXECUTE format('REVOKE ALL ON %I FROM %I', table_name, role_name);
      END LOOP;
    END IF;
  END LOOP;
END $$;

COMMIT;
