-- One row each time an agent takes one of their listings out of our tools:
-- a graphic shared through the phone's share sheet or downloaded, the caption
-- copied or opened in WhatsApp, a window poster or technical sheet printed.
-- Feeds "Statut du jour" (which live listings have not been shared lately)
-- and the landlord report's "partagée N fois".
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260922_listing_shares.sql --write
--
-- ADDITIVE AND IDEMPOTENT. A new table only. web/lib/listingShares.js treats a
-- missing table (42P01) as "nothing recorded yet", so the code can deploy
-- before or after this runs.
--
-- WHAT A ROW IS, AND IS NOT: the agent generated or sent something from
-- lukkaplace.com. It is not proof that anybody saw it — a share sheet can be
-- sent to nobody, a download never posted, a poster never hung. Every surface
-- that prints a count says so.

BEGIN;

CREATE TABLE IF NOT EXISTS listing_shares (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- CASCADE both ways: agents delete their own listings from the dashboard,
  -- and an admin agent deletion takes the agent's own activity with it.
  property_id  bigint      NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
  agent_id     bigint      NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  -- Kept in step with web/lib/listingShareRules.js SHARE_CHANNELS / SHARE_FORMATS.
  channel      text        NOT NULL CHECK (channel IN (
                 'kit_share', 'kit_download', 'kit_whatsapp', 'kit_copy',
                 'menu_whatsapp', 'status_share', 'status_download', 'print'
               )),
  format       text        CHECK (format IS NULL OR format IN (
                 'square', 'story', 'landscape', 'text', 'poster', 'fiche'
               )),
  created_at   timestamptz NOT NULL DEFAULT NOW()
);

-- "When was this listing last shared" (Statut du jour, per listing) and
-- "how often in this window" (the landlord report).
CREATE INDEX IF NOT EXISTS listing_shares_property_created_idx ON listing_shares (property_id, created_at DESC);
-- The per-agent flood cap and dedupe window in recordListingShares.
CREATE INDEX IF NOT EXISTS listing_shares_agent_created_idx ON listing_shares (agent_id, created_at DESC);

-- Supabase grants anon/authenticated on new public tables by default; nothing
-- reads this over the REST API. Same posture as the console_* tables.
DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON listing_shares FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
