-- "Toujours disponible ?" — every time we asked, and every answer.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260929_listing_availability_checks.sql --write
--
-- ADDITIVE AND IDEMPOTENT. One new table.
--
-- web/CLAUDE.md's weekly availability section deliberately left this table out
-- ("nothing reads it — add it when a report needs counts"). It is needed now,
-- for three readers:
--
--  1. The engine's 2-weekly WhatsApp check (services/availabilityCheck.js)
--     must know when it last ASKED about a listing, or it would ask every day.
--     Without this table the job refuses to run rather than spam anybody.
--  2. The agent's response rate and "sans confirmation depuis 28 j" on the
--     admin work queues: two asks in a row with no answer.
--  3. The market data: how a listing left the market (let or sold, and at
--     what price, versus withdrawn by the owner) and whether the customer
--     came through Lukka Place. `properties` only holds the latest state;
--     this holds each answer as it was given.
--
-- WHAT A ROW IS
--  - channel WHATSAPP: one row per question sent, `asked_at` set, answer
--    fields filled in when (if) the agent answers. `delivery` is how it went
--    out (template / buttons / numbered text) — a session message outside
--    the 24h window is accepted by Meta and never arrives, so an unanswered
--    'buttons' ask is not proof the agent ignored it.
--  - channel DASHBOARD: an answer given on lukkaplace.com with no question
--    behind it (`asked_at` NULL).
--
-- `answer` is what the agent said. LET_OR_SOLD and WITHDRAWN are kept apart on
-- purpose: a withdrawal is not a transaction, and folding it in would make
-- time-to-let and achieved prices wrong in exactly the dataset a bank reads.
-- `closed_price` is only ever the agent's own figure; nothing is inferred.

BEGIN;

CREATE TABLE IF NOT EXISTS listing_availability_checks (
  id                   bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id          bigint      NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
  agent_id             bigint      REFERENCES agents (id) ON DELETE SET NULL,
  channel              text        NOT NULL CHECK (channel IN ('WHATSAPP', 'DASHBOARD')),
  delivery             text        CHECK (delivery IS NULL OR delivery IN ('template', 'buttons', 'session-numbered', 'session')),
  asked_at             timestamptz,
  answered_at          timestamptz,
  answer               text        CHECK (answer IS NULL OR answer IN ('AVAILABLE', 'PRICE_CHANGED', 'LET_OR_SOLD', 'WITHDRAWN')),
  previous_price       numeric(14, 2) CHECK (previous_price IS NULL OR previous_price >= 0),
  new_price            numeric(14, 2) CHECK (new_price IS NULL OR new_price > 0),
  closed_price         numeric(14, 2) CHECK (closed_price IS NULL OR closed_price > 0),
  closed_via_platform  boolean,
  created_at           timestamptz NOT NULL DEFAULT NOW(),
  CHECK (channel = 'DASHBOARD' OR asked_at IS NOT NULL),
  CHECK (answer IS NULL OR answered_at IS NOT NULL)
);

-- "When did we last ask about this listing" (the job's 14-day gate) and the
-- latest open question an answer is written onto.
CREATE INDEX IF NOT EXISTS listing_availability_checks_property_asked_idx
  ON listing_availability_checks (property_id, asked_at DESC);
-- Response rate per agent.
CREATE INDEX IF NOT EXISTS listing_availability_checks_agent_idx
  ON listing_availability_checks (agent_id, created_at DESC);

DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON listing_availability_checks FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
