-- Quick replies: an agent's saved WhatsApp messages, opened from a lead or a
-- visit card pre-filled to the CLIENT's number (web/lib/quickReplies.js).
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260922_agent_quick_replies.sql --write
--
-- ADDITIVE AND IDEMPOTENT. A new table only.
--
-- Nothing is seeded. The five French defaults live in code
-- (web/lib/quickReplyRules.js, DEFAULT_QUICK_REPLIES) and are shown to every
-- agent who has no row here. The first time an agent edits, adds or deletes
-- one, the defaults are copied into THEIR rows in the same transaction, each
-- remembering which default it came from (default_key), so the same default
-- can never be copied in twice. A deleted template is soft-deleted
-- (archived_at): "this agent has customised" is EXISTS any row, so deleting
-- every template leaves an empty list instead of bringing the defaults back.

BEGIN;

CREATE TABLE IF NOT EXISTS agent_quick_replies (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id     BIGINT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  title        TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 60),
  body         TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 1000),
  position     INTEGER NOT NULL DEFAULT 0,
  default_key  TEXT CHECK (default_key IS NULL OR default_key ~ '^[a-z][a-z0-9_]{1,40}$'),
  archived_at  TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The sheet and the settings card read one agent's live templates in order.
CREATE INDEX IF NOT EXISTS agent_quick_replies_agent_idx
  ON agent_quick_replies (agent_id, position, id)
  WHERE archived_at IS NULL;

-- One copy of each default per agent, archived or not — what makes the
-- copy-on-first-edit step safe under two tabs racing.
CREATE UNIQUE INDEX IF NOT EXISTS agent_quick_replies_default_key_uq
  ON agent_quick_replies (agent_id, default_key)
  WHERE default_key IS NOT NULL;

DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON agent_quick_replies FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
