-- Admin deletions (agents, packages) and photography allowances per package.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260921_admin_deletions_and_photo_allowances.sql --write
--
-- MUST RUN BEFORE the web deploy that reads packages.photo_sessions_per_month /
-- photo_discount_pct / deleted_at (lib/subscriptions.js selects them).
--
-- ADDITIVE AND IDEMPOTENT.
--
-- 1. IDENTITY SEQUENCES CAUGHT UP. agents.id and packages.id are
--    GENERATED BY DEFAULT AS IDENTITY, but two write paths allocated ids by
--    hand with MAX(id) + 1 (the engine's WhatsApp onboarding for agents,
--    web's createPackage for packages). That never advances the sequence:
--    production had agents_id_seq at 42 with agent #43 already present, so the
--    next web signup would have failed on the primary key. Worse once rows can
--    be deleted — MAX(id) + 1 hands a deleted agent's id, and every engine row
--    still carrying it, to the next person who signs up. Both write paths now
--    use the identity default; this realigns the sequences once. GREATEST so a
--    re-run never moves a sequence backwards.
--
-- 2. PHOTOGRAPHY SERVICES PER PACKAGE. Two separate, real terms an admin sets
--    per plan: sessions included per month, and a discount on the paid
--    Photography Service. 0 means "none", which is every existing plan until
--    someone sets it — nothing is backfilled.
--
-- 3. packages.deleted_at. A package some agency has ever paid for cannot be
--    removed outright: memberships rows are the payment ledger and join to
--    packages for the plan's name. "Supprimer" on such a package stamps this
--    column instead, which hides it from every list and picker while keeping
--    the history readable. A package nobody ever held is deleted for real.

BEGIN;

SELECT setval('agents_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM agents), (SELECT last_value FROM agents_id_seq)));
SELECT setval('packages_id_seq', GREATEST((SELECT COALESCE(MAX(id), 1) FROM packages), (SELECT last_value FROM packages_id_seq)));

ALTER TABLE packages ADD COLUMN IF NOT EXISTS photo_sessions_per_month integer NOT NULL DEFAULT 0;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS photo_discount_pct integer NOT NULL DEFAULT 0;
ALTER TABLE packages ADD COLUMN IF NOT EXISTS deleted_at timestamp;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'packages_photo_sessions_check') THEN
    ALTER TABLE packages ADD CONSTRAINT packages_photo_sessions_check
      CHECK (photo_sessions_per_month BETWEEN 0 AND 100);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'packages_photo_discount_check') THEN
    ALTER TABLE packages ADD CONSTRAINT packages_photo_discount_check
      CHECK (photo_discount_pct BETWEEN 0 AND 100);
  END IF;
END $$;

COMMIT;
