-- An agent's private client book (/compte/agent/clients): the buyers and
-- tenants an agent is working with in their OWN WhatsApp chats — the
-- conversations Lukka Place never sees. Matching against the agent's
-- listings is computed at read time in web/lib/clientMatching.js, so no
-- trigger is needed on properties (listings are written by both the engine
-- and web).
--
-- STRICTLY PRIVATE. Every read and write in web/lib/agentClients.js is scoped
-- to the session's agent id. Nothing here is read by lead dispatch, by
-- another agent, or by any public surface. PostgREST roles are revoked below
-- for the same reason cms_settings revokes them.
--
-- Run with:  node scripts/run-sql-migration.js migrations/20260922_agent_clients.sql --write
--
-- ADDITIVE AND IDEMPOTENT. Two new tables only.

BEGIN;

CREATE TABLE IF NOT EXISTS agent_clients (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id          BIGINT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  name              TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),
  -- Digits-only E.164, the wa_id form lib/phone.js produces.
  phone             TEXT NOT NULL CHECK (phone ~ '^[0-9]{7,15}$'),
  -- Same vocabulary as leads.transaction_type and /listings' ?transaction=.
  transaction_type  TEXT NOT NULL CHECK (transaction_type IN ('location', 'vente')),
  -- Canonical commune names from the engine's GET /locations. Empty = any.
  communes          TEXT[] NOT NULL DEFAULT '{}' CHECK (cardinality(communes) <= 10),
  -- USD, the currency of properties.price.
  budget_min        NUMERIC(14, 2) CHECK (budget_min IS NULL OR budget_min >= 0),
  budget_max        NUMERIC(14, 2) CHECK (budget_max IS NULL OR budget_max >= 0),
  bedrooms          SMALLINT CHECK (bedrooms IS NULL OR bedrooms BETWEEN 0 AND 50),
  notes             TEXT CHECK (notes IS NULL OR char_length(notes) <= 2000),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max)
);

CREATE INDEX IF NOT EXISTS agent_clients_agent_idx ON agent_clients (agent_id, created_at DESC);
-- One entry per number per agent: saving the same client twice is a duplicate,
-- not a second search. Different agents may each hold the same number.
CREATE UNIQUE INDEX IF NOT EXISTS agent_clients_agent_phone_key ON agent_clients (agent_id, phone);

-- "WhatsApp opened on <date>" per client x listing, so an agent does not send
-- the same listing to the same client twice. Recorded when the agent taps the
-- pre-filled wa.me link — we cannot see whether they then pressed send, and
-- the UI says "opened", not "sent".
CREATE TABLE IF NOT EXISTS agent_client_contacts (
  agent_id      BIGINT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  client_id     BIGINT NOT NULL REFERENCES agent_clients (id) ON DELETE CASCADE,
  property_id   BIGINT NOT NULL REFERENCES properties (id) ON DELETE CASCADE,
  contacted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (client_id, property_id)
);

CREATE INDEX IF NOT EXISTS agent_client_contacts_agent_idx ON agent_client_contacts (agent_id);

DO $$
DECLARE
  role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format('REVOKE ALL ON agent_clients FROM %I', role_name);
      EXECUTE format('REVOKE ALL ON agent_client_contacts FROM %I', role_name);
    END IF;
  END LOOP;
END $$;

COMMIT;
