import test, { afterEach, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { calls, enqueue, getPool, reset } from '../support/fakePool.js';
import {
  CHANNEL_FORMATS,
  MAX_IDS_PER_RECORD,
  SHARE_CHANNELS,
  SHARE_COUNT_DEFINITION,
  SHARE_FORMATS,
  coordinateText,
  mapPinUrl,
  normaliseShareRecord,
  printListingUrl,
  shareCountText,
} from '@/lib/listingShareRules';
import { getListingShareCount, getStatusSuggestions, recordListingShares, serialiseSuggestion } from '@/lib/listingShares';
import { buildMandateCaption, buildMandateReport, reportWindow } from '@/lib/marketing/mandateReportCopy';
import { buildReportOps } from '@/lib/marketing/layout';
import { buildPrintSheet, entryCostLines, keyFactRows } from '@/lib/marketing/printSheet';
import { getPrintExtras } from '@/lib/marketing/printSheetData';

/**
 * Statut du jour, share recording (listing_shares), the landlord report's
 * "partagée N fois", and the A4 poster / technical sheet data.
 */

const ROOT = process.cwd();
const pool = getPool();
const realQuery = pool.query;

beforeEach(() => reset());
afterEach(() => {
  pool.query = realQuery;
});

function failWith(code) {
  pool.query = async (text) => {
    calls.push({ text, sql: String(text).replace(/\s+/g, ' ').trim() });
    const err = new Error(`fake ${code}`);
    err.code = code;
    throw err;
  };
}

// ---------------------------------------------------------------------------
// What a share is
// ---------------------------------------------------------------------------

test('a share record is an allow-listed channel × format, with 1..5 distinct positive ids', () => {
  assert.deepEqual(normaliseShareRecord({ listingIds: [305, '305', 12], channel: 'status_share', format: 'story' }), {
    ids: [305, 12],
    channel: 'status_share',
    format: 'story',
  });
  assert.deepEqual(normaliseShareRecord({ listingId: 7, channel: 'print', format: 'fiche' }).ids, [7]);
  assert.equal(normaliseShareRecord({ listingIds: [1], channel: 'status_share', format: 'square' }), null, 'a Status is 9:16 only');
  assert.equal(normaliseShareRecord({ listingIds: [1], channel: 'print', format: 'text' }), null);
  assert.equal(normaliseShareRecord({ listingIds: [1], channel: 'report', format: 'square' }), null, 'the landlord report is not a share');
  assert.equal(normaliseShareRecord({ listingIds: [0, -3, 'x'], channel: 'kit_copy', format: 'text' }), null);
  const tooMany = Array.from({ length: MAX_IDS_PER_RECORD + 1 }, (_, i) => i + 1);
  assert.equal(normaliseShareRecord({ listingIds: tooMany, channel: 'status_download', format: 'story' }), null);
});

test('the migration CHECK constraints list exactly the channels and formats the code accepts', () => {
  const sql = readFileSync(path.join(ROOT, '..', 'migrations', '20260922_listing_shares.sql'), 'utf8');
  const listIn = (column) => {
    const m = sql.match(new RegExp(`${column}\\s+IN \\(([^)]*)\\)`));
    return m[1].match(/'([a-z_]+)'/g).map((s) => s.slice(1, -1)).sort();
  };
  assert.deepEqual(listIn('channel'), [...SHARE_CHANNELS].sort());
  assert.deepEqual(listIn('format'), [...SHARE_FORMATS].sort());
  assert.match(sql, /id\s+bigint\s+GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(sql, /CREATE TABLE IF NOT EXISTS listing_shares/);
  assert.match(sql, /REFERENCES properties \(id\) ON DELETE CASCADE/);
  assert.match(sql, /REFERENCES agents \(id\) ON DELETE CASCADE/);
  assert.equal(Object.keys(CHANNEL_FORMATS).length, SHARE_CHANNELS.length);
});

// ---------------------------------------------------------------------------
// Recording
// ---------------------------------------------------------------------------

test('recording checks ownership and the public filter in the INSERT, and dedupes one tap', async () => {
  await recordListingShares(9, { ids: [305, 306], channel: 'kit_share', format: 'story' });
  const { sql, values } = calls[0];
  assert.match(sql, /^INSERT INTO listing_shares \(property_id, agent_id, channel, format\) SELECT p\.id, \$2, \$3, \$4 FROM properties p/);
  assert.match(sql, /p\.agent_id = \$2/);
  assert.match(sql, /p\.status = 1 AND p\.approve_status = 1/);
  assert.match(sql, /NOT EXISTS \( SELECT 1 FROM listing_shares s WHERE s\.property_id = p\.id AND s\.agent_id = \$2 AND s\.channel = \$3 AND s\.format IS NOT DISTINCT FROM \$4 AND s\.created_at > NOW\(\) - make_interval\(secs => \$5\)/);
  assert.match(sql, /f\.agent_id = \$2 AND f\.created_at > NOW\(\) - interval '1 minute' \) < \$6/);
  assert.deepEqual(values.slice(0, 5), [[305, 306], 9, 'kit_share', 'story', 30]);
});

test('recording before the migration writes nothing and does not throw; other errors do', async () => {
  failWith('42P01');
  assert.equal(await recordListingShares(9, { ids: [1], channel: 'kit_copy', format: 'text' }), 0);
  failWith('57P01');
  await assert.rejects(recordListingShares(9, { ids: [1], channel: 'kit_copy', format: 'text' }));
});

test('the report share count is null — never 0 — when it cannot be read', async () => {
  const w = reportWindow(new Date('2026-09-16T11:42:00Z'));
  enqueue([{ n: 4 }]);
  assert.equal(await getListingShareCount(305, { from: w.from, until: w.end }), 4);
  assert.deepEqual(calls[0].values, [305, '2026-09-10T00:00:00.000Z', '2026-09-17T00:00:00.000Z']);
  failWith('42P01');
  assert.equal(await getListingShareCount(305, { from: w.from, until: w.end }), null);
});

// ---------------------------------------------------------------------------
// Statut du jour
// ---------------------------------------------------------------------------

test('suggestions: own live listings not shared recently, never-shared first, then newest', async () => {
  enqueue([{ id: '305', title: 'Appartement', price: '1000', last_shared_at: null, created_at: new Date() }]);
  const { items, tracked } = await getStatusSuggestions(9);
  assert.equal(tracked, true);
  assert.equal(items.length, 1);
  const { sql, values } = calls[0];
  assert.match(sql, /p\.agent_id = \$1 AND p\.status = 1 AND p\.approve_status = 1 AND COALESCE\(p\.listing_status, 'active'\) NOT IN \('under_offer', 'closed'\)/);
  assert.match(sql, /ls\.last_shared_at IS NULL OR ls\.last_shared_at < NOW\(\) - make_interval\(days => \$2\)/);
  assert.match(sql, /ORDER BY ls\.last_shared_at ASC NULLS FIRST, p\.created_at DESC, p\.id DESC LIMIT \$3/);
  assert.deepEqual(values, [9, 3, 5]);
  assert.deepEqual(serialiseSuggestion(items[0]).id, 305);
});

test('suggestions before the migration fall back to the newest live listings, flagged untracked', async () => {
  let n = 0;
  pool.query = async (text, values) => {
    const sql = String(text).replace(/\s+/g, ' ').trim();
    calls.push({ text, values, sql });
    n += 1;
    if (n === 1) {
      const err = new Error('relation "listing_shares" does not exist');
      err.code = '42P01';
      throw err;
    }
    return { rows: [{ id: 1 }], rowCount: 1 };
  };
  const { items, tracked } = await getStatusSuggestions(9);
  assert.equal(tracked, false);
  assert.equal(items.length, 1);
  assert.doesNotMatch(calls[1].sql, /listing_shares/);
  assert.match(calls[1].sql, /p\.status = 1 AND p\.approve_status = 1/);
});

// ---------------------------------------------------------------------------
// Landlord report: "partagée N fois"
// ---------------------------------------------------------------------------

const NOW = new Date('2026-09-16T11:42:00Z');
const ROW = {
  id: 305, price: 1000, purpose: 'rent', price_period: 'mois', beds: 2, bath: 2, area: null, units_count: null,
  quartier: '24 Novembre', commune: 'Lingwala', status: 1, approve_status: 1, listing_status: null,
};
const COUNTS = {
  current: { views: 42, whatsappClicks: 5, saves: 2, visitRequests: 1 },
  previous: { views: 30, whatsappClicks: 2, saves: 0, visitRequests: 0 },
};
const opts = (shares) => ({ typeText: 'Appartement', brand: { name: 'Makam B', phone: null }, window: reportWindow(NOW), shares });
const measure = (text, { size, weight = 500 }) => String(text).length * size * (weight >= 700 ? 0.6 : 0.52);

test('"partagée N fois" appears only above zero, with what a share is', () => {
  assert.equal(shareCountText(0), null);
  assert.equal(shareCountText(null), null);
  assert.equal(shareCountText(3), 'Partagée 3 fois');

  const report = buildMandateReport(ROW, COUNTS, opts(3));
  assert.equal(report.shareText, 'Partagée 3 fois');
  const caption = buildMandateCaption(ROW, report, COUNTS);
  assert.match(caption, /📣 Partagée 3 fois par l’agent depuis Lukka Place/);
  assert.ok(caption.includes(SHARE_COUNT_DEFINITION));
  assert.match(SHARE_COUNT_DEFINITION, /pas une preuve que quelqu’un l’a vu/);

  for (const shares of [0, null, undefined]) {
    const quiet = buildMandateReport(ROW, COUNTS, opts(shares));
    assert.equal(quiet.shareText, null);
    const text = buildMandateCaption(ROW, quiet, COUNTS);
    assert.doesNotMatch(text, /Partagée/);
    assert.ok(!text.includes(SHARE_COUNT_DEFINITION));
  }
});

test('the report card draws the share line on the status row, inside the canvas', () => {
  const report = buildMandateReport(ROW, COUNTS, opts(12));
  const { width, height, ops } = buildReportOps(report, { measure, hasPhoto: true, hasMark: true });
  const line = ops.find((op) => op.type === 'text' && op.text === 'Partagée 12 fois');
  const status = ops.find((op) => op.type === 'text' && op.text === report.statusText);
  assert.ok(line, 'share line drawn');
  assert.equal(line.y, status.y);
  assert.equal(line.align, 'right');
  assert.ok(line.x - measure(line.text, line) >= 0 && line.x <= width && line.y <= height);
  const none = buildReportOps(buildMandateReport(ROW, COUNTS, opts(0)), { measure, hasPhoto: true, hasMark: true });
  assert.ok(!none.ops.some((op) => op.type === 'text' && /Partagée/.test(op.text)));
});

// ---------------------------------------------------------------------------
// Print pages
// ---------------------------------------------------------------------------

test('printed QR links carry utm_source=print and the medium', () => {
  assert.equal(printListingUrl(305, 'poster'), 'https://lukkaplace.com/listings/305?utm_source=print&utm_medium=poster');
  assert.equal(printListingUrl(305, 'fiche'), 'https://lukkaplace.com/listings/305?utm_source=print&utm_medium=fiche');
  assert.equal(printListingUrl(305, 'evil'), 'https://lukkaplace.com/listings/305?utm_source=print&utm_medium=poster');
});

test('a map link only for a real coordinate', () => {
  assert.equal(mapPinUrl('-4.3250', '15.3120'), 'https://www.google.com/maps/search/?api=1&query=-4.325,15.312');
  assert.equal(coordinateText('-4.3250', '15.3120'), '-4.32500, 15.31200');
  for (const [lat, lng] of [[null, null], ['', '15.3'], ['0', '0'], ['abc', '15'], ['95', '15'], ['-4.3', '200']]) {
    assert.equal(mapPinUrl(lat, lng), null, `${lat},${lng}`);
  }
});

test('entry costs stay three separate lines, never summed, and unstated ones are left out', () => {
  const lines = entryCostLines({ purpose: 'rent', price: 500, price_period: 'mois', deposit_months: 3, advance_months: 1, commission_months: 1 });
  assert.deepEqual(lines.map((l) => [l.key, l.value, l.amount]), [
    ['deposit', '3 mois', `${(1500).toLocaleString('fr-FR')} $`],
    ['advance', '1 mois', '500 $'],
    ['commission', '1 mois', '500 $'],
  ]);
  assert.ok(!lines.some((l) => /5 mois/.test(l.value)), 'no "Garantie : 5 mois"');
  const depositOnly = entryCostLines({ purpose: 'rent', price: 500, price_period: 'an', deposit_months: 3, advance_months: null, commission_months: '' });
  assert.deepEqual(depositOnly.map((l) => [l.key, l.amount]), [['deposit', null]], 'a yearly rent gets no per-month amount');
  assert.deepEqual(entryCostLines({ purpose: 'sale', deposit_months: null }), []);
});

test('key facts list only real counts', () => {
  const rows = keyFactRows({ purpose: 'sale', price: 90000, beds: 0, bath: '', area: '0', units_count: null }, 'Terrain nu');
  assert.deepEqual(rows.map((r) => r.label), ['Type de bien', 'Transaction', 'Prix']);
});

const SUPABASE = 'havyrzfdksabghgbrxfy.supabase.co';
const LISTING = {
  ...ROW,
  title: 'Bel appartement',
  reference: 'Petit Boulevard, 2ᵉ Rue Industrielle',
  deposit_months: 3,
  advance_months: 1,
  commission_months: null,
  featured_image: `https://${SUPABASE}/storage/v1/object/public/Property_images/a.jpg`,
  gallery: ['https://evil.example.com/b.jpg', `https://${SUPABASE}/storage/v1/object/public/Property_images/c.jpg`],
};

test('the print sheet: référence (never repère), real fields only, verified phone only', () => {
  const sheet = buildPrintSheet(
    LISTING,
    { features: [' Eau 24h/24 ', 'eau 24h/24', '', 3], amenities: ['Parking'], address: null, latitude: null, longitude: null },
    { typeText: 'Appartement', brand: { name: 'Makam B', phone: null }, supabaseHost: SUPABASE, medium: 'poster' },
  );
  assert.equal(sheet.headline, 'Appartement à Lingwala');
  assert.equal(sheet.purposeLabel, 'À LOUER');
  assert.deepEqual(sheet.features, ['Eau 24h/24']);
  assert.deepEqual(sheet.location.map((l) => l.label), ['Quartier', 'Commune', 'Référence']);
  assert.equal(sheet.mapUrl, null);
  assert.equal(sheet.agentPhone, null, 'an unverified number is never printed');
  assert.equal(sheet.entryCosts.length, 2);
  assert.equal(sheet.photos.length, 2, 'only optimiser-allowed hosts');
  assert.ok(sheet.cover.endsWith('&w=1920&q=75'));
  assert.equal(sheet.url, 'https://lukkaplace.com/listings/305?utm_source=print&utm_medium=poster');

  const printFiles = ['lib/marketing/printSheet.js', 'components/print/ListingPoster.js', 'components/print/ListingTechSheet.js'];
  for (const file of printFiles) {
    assert.doesNotMatch(readFileSync(path.join(ROOT, file), 'utf8'), /rep[èe]re/i, `${file} says "référence"`);
  }
});

test('print extras are scoped to the owning agent and read feature amenities only', async () => {
  enqueue([{ features: ['x'], amenities: [] }]);
  await getPrintExtras(9, 305);
  const { sql, values } = calls[0];
  assert.match(sql, /WHERE p\.id = \$2 AND p\.agent_id = \$3/);
  assert.match(sql, /pa\.amenity_id NOT BETWEEN 21 AND 44/);
  assert.deepEqual(values, [20, 305, 9]);
});

test('print pages: A4 page size, a print button, and the poster/sheet reachable from the kit and the menu', () => {
  const styles = readFileSync(path.join(ROOT, 'components/print/PrintStyles.js'), 'utf8');
  assert.match(styles, /@page \{ size: A4; margin: 0; \}/);
  assert.match(styles, /aspect-ratio: 210 \/ 297/);
  const toolbar = readFileSync(path.join(ROOT, 'components/print/PrintToolbar.js'), 'utf8');
  assert.match(toolbar, /window\.print\(\)/);
  for (const file of ['components/AgentListingShareKit.js', 'components/AgentListingActionsMenu.js']) {
    const src = readFileSync(path.join(ROOT, file), 'utf8');
    assert.match(src, /\/compte\/agent\/biens\/\$\{[a-zA-Z.]+\}\/affiche/, `${file} links the poster`);
    assert.match(src, /\/compte\/agent\/biens\/\$\{[a-zA-Z.]+\}\/fiche/, `${file} links the sheet`);
  }
});

test('the share kit records after the share, fire-and-forget, and never for the landlord report', () => {
  const kit = readFileSync(path.join(ROOT, 'components/AgentListingShareKit.js'), 'utf8');
  assert.match(kit, /recordListingSharesAction\(\{ listingIds: \[listingId\], \.\.\.record \}\)\.catch\(\(\) => \{\}\)/);
  assert.match(kit, /await navigator\.share\(\{ files: \[file\], text \}\);\s*recordShare\(record && \{ \.\.\.record, channel: 'kit_share' \}\)/);
  assert.match(kit, /onClick=\{\(\) => shareFile\(reportFile, report\.caption, 'report'\)\}/, 'report shares pass no record');
  assert.doesNotMatch(kit, /await recordListingSharesAction/);
});
